spring.datasource.url=jdbc:mysql://localhost:3306/agri_connect
spring.datasource.username=root
spring.datasource.password=YOUR_DB_PASSWORD

jwt.secret=YOUR_SECRET_KEY

payu.key=YOUR_KEY
payu.salt=YOUR_SALT

groq.api.key=YOUR_API_KEY

twilio.account-sid=YOUR_SID
twilio.auth-token=YOUR_TOKEN

fast2sms.api.key=YOUR_API_KEY

spring.mail.username=your_email@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

datagov.api.key=YOUR_API_KEY